---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosqueries/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosqueries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosservices/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosservices/status
  verbs:
  - get
  - patch
  - update
